In [ ]:
!pip install geemap

Requirement already satisfied: geemap in /usr/local/lib/python3.10/dist-packages (0.29.6)
Requirement already satisfied: bqplot in /usr/local/lib/python3.10/dist-packages (from geemap) (0.12.42)
Requirement already satisfied: colour in /usr/local/lib/python3.10/dist-packages (from geemap) (0.1.5)
Requirement already satisfied: earthengine-api>=0.1.347 in /usr/local/lib/python3.10/dist-packages (from geemap) (0.1.384)
Requirement already satisfied: eerepr>=0.0.4 in /usr/local/lib/python3.10/dist-packages (from geemap) (0.0.4)
Requirement already satisfied: folium>=0.13.0 in /usr/local/lib/python3.10/dist-packages (from geemap) (0.14.0)
Requirement already satisfied: geocoder in /usr/local/lib/python3.10/dist-packages (from geemap) (1.38.1)
Requirement already satisfied: ipyevents in /usr/local/lib/python3.10/dist-packages (from geemap) (2.0.2)
Requirement already satisfied: ipyfilechooser>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from geemap) (0.6.0)
Requirement already satisfied: ipyleaflet>=0.17.0 in /usr/local/lib/python3.10/dist-packages (from geemap) (0.18.1)
Requirement already satisfied: ipytree in /usr/local/lib/python3.10/dist-packages (from geemap) (0.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from geemap) (3.7.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from geemap) (1.23.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from geemap) (1.5.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from geemap) (5.15.0)
Requirement already satisfied: pyperclip in /usr/local/lib/python3.10/dist-packages (from geemap) (1.8.2)
Requirement already satisfied: pyshp>=2.1.3 in /usr/local/lib/python3.10/dist-packages (from geemap) (2.3.1)
Requirement already satisfied: python-box in /usr/local/lib/python3.10/dist-packages (from geemap) (7.1.1)
Requirement already satisfied: scooby in /usr/local/lib/python3.10/dist-packages (from geemap) (0.9.2)
Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.10/dist-packages (from earthengine-api>=0.1.347->geemap) (2.8.0)
Requirement already satisfied: google-api-python-client>=1.12.1 in /usr/local/lib/python3.10/dist-packages (from earthengine-api>=0.1.347->geemap) (2.84.0)
Requirement already satisfied: google-auth>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from earthengine-api>=0.1.347->geemap) (2.17.3)
Requirement already satisfied: google-auth-httplib2>=0.0.3 in /usr/local/lib/python3.10/dist-packages (from earthengine-api>=0.1.347->geemap) (0.1.1)
Requirement already satisfied: httplib2<1dev,>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from earthengine-api>=0.1.347->geemap) (0.22.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from earthengine-api>=0.1.347->geemap) (2.31.0)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from folium>=0.13.0->geemap) (0.7.0)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.10/dist-packages (from folium>=0.13.0->geemap) (3.1.2)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.10/dist-packages (from ipyfilechooser>=0.6.0->geemap) (7.7.1)
Requirement already satisfied: traittypes<3,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from ipyleaflet>=0.17.0->geemap) (0.2.1)
Requirement already satisfied: xyzservices>=2021.8.1 in /usr/local/lib/python3.10/dist-packages (from ipyleaflet>=0.17.0->geemap) (2023.10.1)
Requirement already satisfied: traitlets>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from bqplot->geemap) (5.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->geemap) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->geemap) (2023.3.post1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from geocoder->geemap) (8.1.7)
Requirement already satisfied: future in /usr/local/lib/python3.10/dist-packages (from geocoder->geemap) (0.18.3)
Requirement already satisfied: ratelim in /usr/local/lib/python3.10/dist-packages (from geocoder->geemap) (0.1.6)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from geocoder->geemap) (1.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->geemap) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->geemap) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->geemap) (4.47.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->geemap) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->geemap) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->geemap) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->geemap) (3.1.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->geemap) (8.2.3)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /usr/local/lib/python3.10/dist-packages (from google-api-python-client>=1.12.1->earthengine-api>=0.1.347->geemap) (2.11.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from google-api-python-client>=1.12.1->earthengine-api>=0.1.347->geemap) (4.1.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.4.1->earthengine-api>=0.1.347->geemap) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.4.1->earthengine-api>=0.1.347->geemap) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.4.1->earthengine-api>=0.1.347->geemap) (4.9)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (5.5.6)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.6.6)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (7.34.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.0.9)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.9->folium>=0.13.0->geemap) (2.1.3)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage->earthengine-api>=0.1.347->geemap) (2.3.3)
Requirement already satisfied: google-resumable-media>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage->earthengine-api>=0.1.347->geemap) (2.7.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->earthengine-api>=0.1.347->geemap) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->earthengine-api>=0.1.347->geemap) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->earthengine-api>=0.1.347->geemap) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->earthengine-api>=0.1.347->geemap) (2023.11.17)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ratelim->geocoder->geemap) (4.4.2)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.12.1->earthengine-api>=0.1.347->geemap) (1.62.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client>=1.12.1->earthengine-api>=0.1.347->geemap) (3.20.3)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/dist-packages (from google-resumable-media>=2.3.2->google-cloud-storage->earthengine-api>=0.1.347->geemap) (1.5.0)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.1.12)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.3.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (67.7.2)
Collecting jedi>=0.16 (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap)
  Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 7.3 MB/s eta 0:00:00
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.0.43)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.16.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.1.6)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.9.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->earthengine-api>=0.1.347->geemap) (0.5.1)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.10/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.5.5)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.8.3)
Requirement already satisfied: pyzmq<25,>=17 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (23.2.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (23.1.0)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (5.5.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (5.9.2)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.5.4)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.5.8)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.18.0)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.19.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.0.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.12)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core>=4.6.1->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.1.0)
Requirement already satisfied: jupyter-server>=1.8 in /usr/local/lib/python3.10/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.24.0)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.10/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.2.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.9.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.11.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (6.1.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.7.1)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.4)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.3.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.8.4)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.9.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.5.0)
Requirement already satisfied: tinycss2 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.2.1)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.10/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.19.0)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.10/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (4.19.2)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.10/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (21.2.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2023.11.2)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.32.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.15.2)
Requirement already satisfied: anyio<4,>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (3.7.1)
Requirement already satisfied: websocket-client in /usr/local/lib/python3.10/dist-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.7.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.16.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.5)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (0.5.1)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.3.0)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (1.2.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->ipyfilechooser>=0.6.0->geemap) (2.21)
Installing collected packages: jedi
Successfully installed jedi-0.19.1

In [ ]:
import geemap
import ee

In [ ]:
ee.Authenticate()

In [ ]:
ee.Initialize(project='first-parser-394719')

In [ ]:
#for testing
Map = geemap.Map(center=[31.5204, 74.3587], zoom=9)
Map

Map(center=[31.5204, 74.3587], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=SearchDa…

In [ ]:
sentinel2 = ee.ImageCollection("COPERNICUS/S2_SR");

USDA_SoilData = ee.ImageCollection("NASA_USDA/HSL/SMAP10KM_soil_moisture");
# 30m Resolution for elevation
NASA_srtm = ee.Image("USGS/SRTMGL1_003");

#Modis
modis_lai_data = ee.ImageCollection('MODIS/061/MCD15A3H');
modis_vegetation_data = ee.ImageCollection("MODIS/061/MYD13Q1")

# Load Landsat 8 and 9 image collections
landsat8 = ee.ImageCollection("LANDSAT/LC08/C02/T1_L2")
landsat9 = ee.ImageCollection("LANDSAT/LC09/C02/T1_L2")

# Load the sugarcane and other feature collections
sugarcane_tx = ee.FeatureCollection("projects/ee-sp20-bcs-003/assets/TX_intersection_5Y")

In [ ]:
sugarcane_tx.size().getInfo()

453

# Calculating Indices from Landset 8 and 9

In [ ]:
# Function to cloud mask image
def cloud_mask_landsat(image):
    qa = image.select('QA_PIXEL')
    cloud = 1 << 3
    cirrus = 1 << 9
    mask = qa.bitwiseAnd(cloud).eq(0).And(qa.bitwiseAnd(cirrus).eq(0))
    return image.updateMask(mask)

In [ ]:
# Function to calculate spectral indices
def calculate_indices_landsat(img):

    ndvi = img.normalizedDifference(['SR_B5', 'SR_B4']).rename('NDVI')
    gndvi = img.normalizedDifference(['SR_B5', 'SR_B3']).rename('GNDVI')
    evi = img.expression(
        '2.5 * ((NIR - RED) / (NIR + 6 * RED - 7.5 * BLUE + 1))',
        {
            'NIR': img.select('SR_B5'),
            'RED': img.select('SR_B4'),
            'BLUE': img.select('SR_B2')
        }
    ).rename('EVI')
    nbr = img.normalizedDifference(['SR_B5', 'SR_B7']).rename('NBR')
    ndmi = img.normalizedDifference(['SR_B5', 'SR_B6']).rename('NDMI')
    ndwi = img.normalizedDifference(['SR_B3', 'SR_B5']).rename('NDWI')
    ndbi = img.normalizedDifference(['SR_B6', 'SR_B5']).rename('NDBI')
    ndbai = img.normalizedDifference(['SR_B6', 'SR_B7']).rename('NDBaI')
    mndwi = img.normalizedDifference(['SR_B3', 'SR_B6']).rename('MNDWI')
    return img.addBands([ndvi,gndvi,evi,nbr, ndmi, ndwi, ndbi, ndbai, mndwi])

In [ ]:
landsat8=landsat8.map(cloud_mask_landsat)
landsat8=landsat8.map(calculate_indices_landsat)

landsat9=landsat9.map(cloud_mask_landsat)
landsat9=landsat9.map(calculate_indices_landsat)

# Calculating indices from Sentinel 2 Setallite

In [ ]:
def sentinel2_bands_calculations(image):
    ndvi = image.normalizedDifference(['B8', 'B4']).rename('NDVI')
    gndvi = image.normalizedDifference(['B8', 'B3']).rename('GNDVI')
    evi = image.expression(
        '2.5 * ((NIR - RED) / (NIR + 6 * RED - 7.5 * BLUE + 1))',
        {
            'NIR': image.select('B8'),
            'RED': image.select('B4'),
            'BLUE': image.select('B2')
        }
    ).rename('EVI')
    red = image.select('B4')  # Red band (Sentinel-2 band 4)
    nir = image.select('B8')  # NIR band (Sentinel-2 band 8)
    savi = nir.subtract(red).divide(nir.add(red).add(0.5)).multiply(1.5).rename('SAVI')
    return image.addBands([ndvi, gndvi, evi, savi])

def mask_clouds(image):
    QA60 = image.select(['QA60'])
    cloud_bit_mask = 1 << 10
    cirrus_bit_mask = 1 << 11
    mask = QA60.bitwiseAnd(cloud_bit_mask).eq(0).And(QA60.bitwiseAnd(cirrus_bit_mask).eq(0))
    return image.updateMask(mask)

def calculate_indices(image):
    # Calculate VCI (Vegetation Condition Index)
    VCI = image.expression('(NDVI - NDVI_min) / (NDVI_max - NDVI_min) * 100',
                           {'NDVI': image.select('NDVI'),
                            'NDVI_min': 0,
                            'NDVI_max': 0.8}).rename('VCI')

    # Calculate Transformed Vegetation Index (TVI)
    TVI = image.expression('0.5 * (NIR - RED) / (NIR + RED + 0.5)',
                           {'NIR': image.select('B8'),
                            'RED': image.select('B4')}).rename('TVI')

    # Calculate Brightness Index (BI)
    BI = image.expression('sqrt((RED**2) + (NIR**2))',
                          {'RED': image.select('B4'),
                           'NIR': image.select('B8')}).rename('BI')

    # Calculate Second Brightness Index (BI2)
    BI2 = image.expression('(RED + NIR) / 2',
                           {'RED': image.select('B4'),
                            'NIR': image.select('B8')}).rename('BI2')

    # Calculate Color Index (CI)
    CI = image.expression('(NIR / RED) - 1',
                          {'NIR': image.select('B8'),
                           'RED': image.select('B4')}).rename('CI')

    # Calculate Clay Index (CI1)
    CI1 = image.expression('(RED / NIR) - 1',
                           {'RED': image.select('B4'),
                            'NIR': image.select('B8')}).rename('CI1')

    # Calculate SATVI (Soil Adjusted Total Vegetation Index)
    SATVI = image.expression('(NIR - RED - 0.5) / (NIR + RED + 0.5)',
                             {'NIR': image.select('B8'),
                              'RED': image.select('B4')}).rename('SATVI')

    # Calculate HVSI (Hue, Value, and Intensity)
    HVSI = image.expression('sqrt((NIR - RED)**2 + (NIR - GREEN)*(RED - GREEN))',
                            {'NIR': image.select('B8'),
                             'RED': image.select('B4'),
                             'GREEN': image.select('B3')}).rename('HVSI')

    # Calculate SOCI (Soil Organic Carbon Index)
    SOCI = image.expression('(NIR / RED) * (1 + RED - GREEN)',
                            {'NIR': image.select('B8'),
                             'RED': image.select('B4'),
                             'GREEN': image.select('B3')}).rename('SOCI')

    # Calculate ASI (Agricultural Stress Index)
    ASI = image.expression('RED - (GREEN + BLUE) / 2',
                           {'RED': image.select('B4'),
                            'GREEN': image.select('B3'),
                            'BLUE': image.select('B2')}).rename('ASI')

    # Calculate BSI (Bare Soil Index)
    BSI = image.expression('1 - (NIR + 0.05) / (RED + 0.05)',
                           {'NIR': image.select('B8'),
                            'RED': image.select('B4')}).rename('BSI')

    # Calculate MSAVI (Modified Soil Adjusted Vegetation Index)
    MSAVI = image.expression('(2 * NIR + 1 - sqrt((2 * NIR + 1)**2 - 8 * (NIR - RED))) / 2',
                             {'NIR': image.select('B8'),
                              'RED': image.select('B4')}).rename('MSAVI')

    return image.addBands([VCI, TVI, BI, BI2, CI, CI1, SATVI, HVSI, SOCI, ASI, BSI, MSAVI])


sentinel2 = sentinel2.map(mask_clouds)
sentinel2 = sentinel2.map(sentinel2_bands_calculations)
sentinel2 = sentinel2.map(calculate_indices)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Splitting 43000 into sets so it can be used
total_count = sugarcane_la.size().getInfo()

# Calculate the number of features in each split
split_count = int(total_count / 10)

# Create a list to store the splits
sugarcane_sets = []

last_index = 0
# Iterate over 10 partitions
for i in range(1, 11):
    # Calculate the starting and ending index for each split
    start_index = (i - 1) * split_count
    end_index = i * split_count


    # Filter the FeatureCollection to get the current split
    split = sugarcane_la.toList(split_count, start_index)
    sugarcane_sets.append(split)

NameError: name 'sugarcane_la' is not defined

In [ ]:
def normalize_modis_value(x, min_val=-2000, max_val=10000, new_min=-1, new_max=1):
    normalized_value = ((x - min_val) / (max_val - min_val)) * (new_max - new_min) + new_min
    return normalized_value

In [ ]:
collection_years = [


    {
        'start_date': '2018-01-01',
        'end_date': '2018-12-31',
        'year':2018,
    },

    {
        'start_date': '2019-01-01',
        'end_date': '2019-12-31',
        'year':2019,
    },

    {
        'start_date': '2021-01-01',
        'end_date': '2021-12-31',
        'year':2021,
    },

    {
        'start_date': '2022-01-01',
        'end_date': '2022-12-31',
        'year':2022,
    }
]

In [ ]:
feature_data = []
index = 1
for year in collection_years:

  start_date = year['start_date']
  end_date = year['end_date']

  sentinel2_data = sentinel2 \
  .filterDate(start_date, end_date)


  landsat8_data = landsat8 \
  .filterDate(start_date, end_date)

  # landsat9_data = landsat9 \
  # .filterDate(start_date, end_date)

  modis_lai = modis_lai_data \
  .filterDate(start_date, end_date)

  modis_vegetation = modis_vegetation_data \
  .filterDate(start_date, end_date)

  USDA_SoilData_data = USDA_SoilData \
  .filterDate(start_date, end_date)

  landsat8_imagery = landsat8_data.mosaic().select(['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7','NBR','NDVI','GNDVI','EVI','NDMI','NDWI','NDBI','NDBaI','MNDWI'])
  # landsat9_imagery = landsat9_data.mosaic().select(['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7','NBR','NDVI','GNDVI','EVI','NDMI','NDWI','NDBI','NDBaI','MNDWI'])
  sentinel_2_imagery = sentinel2_data.median().select(['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'B11', 'B12', 'NDVI', 'EVI', 'GNDVI','SAVI','VCI', 'TVI', 'BI', 'BI2', 'CI', 'CI1', 'SATVI', 'HVSI', 'SOCI', 'ASI', 'BSI', 'MSAVI'])
  modis_lai_imagery = modis_lai.mosaic().select(['Lai'])
  modis_vegetation_imagery = modis_vegetation.mosaic().select('NDVI','EVI')
  USDA_imagery = USDA_SoilData_data.mosaic().select(['ssm'])



  field_id = 1

  for set in sugarcane_sets:

    table = set.getInfo()
    for record in table:

      polygon = ee.Feature(record)
      area = polygon.getInfo()['properties']['area'] #In acres
      roi = polygon.geometry()

      elevation = NASA_srtm.clip(roi).log().divide(10).clamp(0, 1).toFloat()

      landsat8_stats = landsat8_imagery.select(['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7','NBR','NDVI','GNDVI','EVI','NDMI','NDWI','NDBI','NDBaI','MNDWI']) \
      .reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=30)

      # landsat9_stats = landsat9_imagery.select(['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7','NBR','NDVI','GNDVI','EVI','NDMI','NDWI','NDBI','NDBaI','MNDWI']) \
      # .reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=30)

      sentinel_2_stats = sentinel_2_imagery.select(['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'B11', 'B12', 'NDVI', 'EVI', 'GNDVI','SAVI','VCI', 'TVI', 'BI', 'BI2', 'CI', 'CI1', 'SATVI', 'HVSI', 'SOCI', 'ASI', 'BSI', 'MSAVI']) \
      .addBands(elevation) \
      .reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=30)

      modis_lai_stats = modis_lai_imagery.select(['Lai']) \
      .reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=30)

      modis_vegetation_stats = modis_vegetation_imagery.select(['NDVI','EVI']) \
      .reduceRegion(reducer=ee.Reducer.mean(),geometry=roi,scale=30)


      USDA_stats = USDA_imagery.select(['ssm']) \
      .reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=30)

      indices = sentinel_2_stats.getInfo()
      modis_lai_indices = modis_lai_stats.getInfo()
      modis_vegetation_indices = modis_vegetation_stats.getInfo()
      usda_indices = USDA_stats.getInfo()
      landsat8_indices = landsat8_stats.getInfo()
      # landsat9_indices = landsat9_stats.getInfo()

      dictionary = {}
      dictionary['field_id'] = field_id
      dictionary['coordinates']= roi.getInfo()['coordinates'][0]
      dictionary['date'] = year['year']
      dictionary['Annual Sentinel 2 NDVI'] = indices.get('NDVI')
      dictionary['Annual Sentinel 2 EVI'] = indices.get('EVI')
      dictionary['Annual Sentinel 2 GNDVI'] = indices.get('GNDVI')
      dictionary['Annual Sentinel 2 SAVI'] = indices.get('SAVI')
      dictionary['Annual Sentinel 2 B1'] = indices.get('B1')
      dictionary['Annual Sentinel 2 B2'] = indices.get('B2')
      dictionary['Annual Sentinel 2 B3'] = indices.get('B3')
      dictionary['Annual Sentinel 2 B4'] = indices.get('B4')
      dictionary['Annual Sentinel 2 B5'] = indices.get('B5')
      dictionary['Annual Sentinel 2 B6'] = indices.get('B6')
      dictionary['Annual Sentinel 2 B7'] = indices.get('B7')
      dictionary['Annual Sentinel 2 B8'] = indices.get('B8')
      dictionary['Annual Sentinel 2 B9'] = indices.get('B9')
      dictionary['Annual Sentinel 2 B11'] = indices.get('B11')
      dictionary['Annual Sentinel 2 B12'] = indices.get('B12')

      dictionary['Annual Sentinel 2 VCI'] = indices.get('VCI')
      dictionary['Annual Sentinel 2 TVI'] = indices.get('TVI')
      dictionary['Annual Sentinel 2 BI'] = indices.get('BI')
      dictionary['Annual Sentinel 2 BI2'] = indices.get('BI2')
      dictionary['Annual Sentinel 2 CI'] = indices.get('CI')
      dictionary['Annual Sentinel 2 CI1'] = indices.get('CI1')
      dictionary['Annual Sentinel 2 SATVI'] = indices.get('SATVI')
      dictionary['Annual Sentinel 2 HVSI'] = indices.get('HVSI')
      dictionary['Annual Sentinel 2 SOCI'] = indices.get('SOCI')
      dictionary['Annual Sentinel 2 ASI'] = indices.get('ASI')
      dictionary['Annual Sentinel 2 BSI'] = indices.get('BSI')
      dictionary['Annual Sentinel 2 MSAVI'] = indices.get('MSAVI')

      dictionary['Annual Sentinel 2 Elevation'] = indices.get('elevation')

      dictionary['Annual SR8_B1'] = landsat8_indices.get('SR_B1')
      dictionary['Annual SR8_B2'] = landsat8_indices.get('SR_B2')
      dictionary['Annual SR8_B3'] = landsat8_indices.get('SR_B3')
      dictionary['Annual SR8_B4'] = landsat8_indices.get('SR_B4')
      dictionary['Annual SR8_B5'] = landsat8_indices.get('SR_B5')
      dictionary['Annual SR8_B6'] = landsat8_indices.get('SR_B6')
      dictionary['Annual SR8_B7'] = landsat8_indices.get('SR_B7')
      dictionary['Annual NBR_8'] = landsat8_indices.get('NBR')
      dictionary['Annual NDMI_8'] = landsat8_indices.get('NDMI')
      dictionary['Annual NDWI_8'] = landsat8_indices.get('NDWI')
      dictionary['Annual NDBI_8'] = landsat8_indices.get('NDBI')
      dictionary['Annual NDBaI_8'] = landsat8_indices.get('NDBaI')
      dictionary['Annual MNDWI_8'] = landsat8_indices.get('MNDWI')
      dictionary['Annual NDVI_8'] = landsat8_indices.get('NDVI')
      dictionary['Annual GNDVI_8'] = landsat8_indices.get('GNDVI')
      dictionary['Annual EVI_8'] = landsat8_indices.get('EVI')






      # dictionary['Annual SR9_B1'] = landsat9_indices.get('SR_B1')
      # dictionary['Annual SR9_B2'] = landsat9_indices.get('SR_B2')
      # dictionary['Annual SR9_B3'] = landsat9_indices.get('SR_B3')
      # dictionary['Annual SR9_B4'] = landsat9_indices.get('SR_B4')
      # dictionary['Annual SR9_B5'] = landsat9_indices.get('SR_B5')
      # dictionary['Annual SR9_B6'] = landsat9_indices.get('SR_B6')
      # dictionary['Annual SR9_B7'] = landsat9_indices.get('SR_B7')
      # dictionary['Annual NBR_9'] = landsat9_indices.get('NBR')
      # dictionary['Annual NDMI_9'] = landsat9_indices.get('NDMI')
      # dictionary['Annual NDWI_9'] = landsat9_indices.get('NDWI')
      # dictionary['Annual NDBI_9'] = landsat9_indices.get('NDBI')
      # dictionary['Annual NDBaI_9'] = landsat9_indices.get('NDBaI')
      # dictionary['Annual MNDWI_9'] = landsat9_indices.get('MNDWI')
      # dictionary['Annual NDVI_9'] = landsat9_indices.get('NDVI')
      # dictionary['Annual GNDVI_9'] = landsat9_indices.get('GNDVI')
      # dictionary['Annual EVI_9'] = landsat9_indices.get('EVI')

      dictionary['Annual MODIS LAI'] = modis_lai_indices.get('Lai')

      dictionary['Annual MODIS NDVI'] = normalize_modis_value(modis_vegetation_indices.get('NDVI'))
      dictionary['Annual MODIS EVI'] = normalize_modis_value(modis_vegetation_indices.get('EVI'))

      dictionary['Annual MOISTURE'] = usda_indices.get('ssm')

      dictionary['Area'] = area

      feature_data.append(dictionary)
      field_id = field_id + 1
    df = pd.DataFrame(feature_data)
    feature_data = []
    # Save the DataFrame as a CSV file
    df.to_csv(f'Louisiana_4Y_Records_{index}.csv', index=False)

    # Download the CSV file in Google Colab
    from google.colab import files
    files.download(f'Louisiana_4Y_Records_{index}.csv')
    index = index + 1
    print("Field ID with Year", field_id, start_date)

Field ID with Year 1481 2018-01-01

Field ID with Year 2961 2018-01-01

Field ID with Year 4441 2018-01-01

Field ID with Year 5921 2018-01-01

Field ID with Year 7401 2018-01-01

Field ID with Year 8881 2018-01-01

WARNING:googleapiclient.http:Sleeping 0.29 seconds before retry 1 of 5 for request: POST https://earthengine.googleapis.com/v1/projects/earthengine-legacy/value:compute?prettyPrint=false&alt=json, after 502

Field ID with Year 10361 2018-01-01

In [ ]:
len(feature_data)

17

In [ ]:
df = pd.DataFrame(feature_data)

Empty DataFrame
Columns: [field_id, coordinates, date, Annual Sentinel 2 NDVI, Annual Sentinel 2 EVI, Annual Sentinel 2 GNDVI, Annual Sentinel 2 SAVI, Annual Sentinel 2 B1, Annual Sentinel 2 B2, Annual Sentinel 2 B3, Annual Sentinel 2 B4, Annual Sentinel 2 B5, Annual Sentinel 2 B6, Annual Sentinel 2 B7, Annual Sentinel 2 B8, Annual Sentinel 2 B9, Annual Sentinel 2 B11, Annual Sentinel 2 B12, Annual Sentinel 2 VCI, Annual Sentinel 2 TVI, Annual Sentinel 2 BI, Annual Sentinel 2 BI2, Annual Sentinel 2 CI, Annual Sentinel 2 CI1, Annual Sentinel 2 SATVI, Annual Sentinel 2 HVSI, Annual Sentinel 2 SOCI, Annual Sentinel 2 ASI, Annual Sentinel 2 BSI, Annual Sentinel 2 MSAVI, Annual Sentinel 2 Elevation, Annual SR8_B1, Annual SR8_B2, Annual SR8_B3, Annual SR8_B4, Annual SR8_B5, Annual SR8_B6, Annual SR8_B7, Annual NBR_8, Annual NDMI_8, Annual NDWI_8, Annual NDBI_8, Annual NDBaI_8, Annual MNDWI_8, Annual NDVI_8, Annual GNDVI_8, Annual EVI_8, Annual MODIS LAI, Annual MODIS NDVI, Annual MODIS EVI, Annual MOISTURE, Area]
Index: []

[0 rows x 52 columns]

In [ ]:
feature_weights = {
        'field_id': 0,
        'coorrdinates': 0,
        'date': 0,
        'Annual NDVI': 0.25,
        'Annual EVI': 0.2,
        'Annual GNDVI': 0.15,
        'Annual SAVI': 0.15,
        'Annual B1': 0.05,
        'Annual B2': 0.05,
        'Annual B3': 0.05,
        'Annual B4': 0.05,
        'Annual B5': 0.05,
        'Annual B6': 0.05,
        'Annual B7': 0.05,
        'Annual B8': 0.05,
        'Annual B9': 0.05,
        'Annual B11': 0.05,
        'Annual B12': 0.05,
        'Annual SR8_B1': 0.05,
        'Annual SR8_B2': 0.05,
        'Annual SR8_B3': 0.05,
        'Annual SR8_B4': 0.05,
        'Annual SR8_B5': 0.05,
        'Annual SR8_B6': 0.05,
        'Annual SR8_B7': 0.05,
        'Annual NBR_8': 0.03,
        'Annual NDVI_8':0.25,
        'Annual EVI_8':0.2,
        'Annual GNDVI_8':0.15,
        'Annual NDMI_8': 0.04,
        'Annual NDWI_8': 0.04,
        'Annual NDBI_8': 0.03,
        'Annual NDBaI_8': 0.02,
        'Annual MNDWI_8': 0.03,
        'Annual SR9_B1': 0.05,
        'Annual SR9_B2': 0.05,
        'Annual SR9_B3': 0.05,
        'Annual SR9_B4': 0.05,
        'Annual SR9_B5': 0.05,
        'Annual SR9_B6': 0.05,
        'Annual SR9_B7': 0.05,
        'Annual NBR_9': 0.03,
        'Annual NDVI_9':0.25,
        'Annual EVI_9':0.2,
        'Annual GNDVI_9':0.15,
        'Annual NDMI_9': 0.04,
        'Annual NDWI_9': 0.04,
        'Annual NDBI_9': 0.03,
        'Annual NDBaI_9': 0.02,
        'Annual MNDWI_9': 0.03,
        'Annual LAI': 0.2,
        'Annual MOISTURE': 0.1,
        'Area': 0.3,
        'Elevation': 0.1,
        'Annual VCI': 0.1,
        'Annual TVI': 0.1,
        'Annual BI': 0.05,
        'Annual BI2': 0.05,
        'Annual CI': 0.05,
        'Annual CI1': 0.05,
        'Annual SATVI': 0.1,
        'Annual HVSI': 0.1,
        'Annual SOCI': 0.05,
        'Annual ASI': 0.05,
        'Annual BSI': 0.05,
        'Annual MSAVI': 0.1,
        'Annual MODIS NDVI':0.25,
        'Annual MODIS EVI':0.2
    }

In [ ]:
# Create a feature collection for the specified state (Florida in this case)
florida = ee.FeatureCollection('TIGER/2018/States') \
    .filter(ee.Filter.eq('STUSPS', 'TX'))
roi = florida.geometry()
# Print the feature collection (optional)

In [ ]:
start_date = '2023-01-01'
end_date = '2023-12-01'
yield_annually = 30

sentinel2_data = sentinel2 \
.filterDate(start_date, end_date)

landsat8_data = landsat8 \
.filterDate(start_date, end_date)

landsat9_data = landsat9 \
.filterDate(start_date, end_date)

modis_lai = modis_lai_data \
.filterDate(start_date, end_date)

modis_vegetation = modis_vegetation_data \
.filterDate(start_date, end_date)

USDA_SoilData_data = USDA_SoilData \
.filterDate(start_date, end_date)

landsat8_imagery = landsat8_data.mosaic().select(['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7','NBR','NDVI','GNDVI','EVI','NDMI','NDWI','NDBI','NDBaI','MNDWI'])
landsat9_imagery = landsat9_data.mosaic().select(['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7','NBR','NDVI','GNDVI','EVI','NDMI','NDWI','NDBI','NDBaI','MNDWI'])
sentinel_2_imagery = sentinel2_data.mosaic().select(['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'B11', 'B12', 'NDVI', 'EVI', 'GNDVI','SAVI','VCI', 'TVI', 'BI', 'BI2', 'CI', 'CI1', 'SATVI', 'HVSI', 'SOCI', 'ASI', 'BSI', 'MSAVI'])
modis_lai_imagery = modis_lai.mosaic().select(['Lai'])
modis_vegetation_imagery = modis_vegetation.mosaic().select('NDVI','EVI')
USDA_imagery = USDA_SoilData_data.mosaic().select(['ssm'])


elevation = NASA_srtm.clip(roi).log().divide(10).clamp(0, 1).toFloat()

landsat8_stats = landsat8_imagery.select(['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7','NBR','NDVI','GNDVI','EVI','NDMI','NDWI','NDBI','NDBaI','MNDWI']) \
.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=100,maxPixels=1e10)

landsat9_stats = landsat9_imagery.select(['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7','NBR','NDVI','GNDVI','EVI','NDMI','NDWI','NDBI','NDBaI','MNDWI']) \
.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=100,maxPixels=1e10)

sentinel_2_stats = sentinel_2_imagery.select(['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'B11', 'B12', 'NDVI', 'EVI', 'GNDVI','SAVI','VCI', 'TVI', 'BI', 'BI2', 'CI', 'CI1', 'SATVI', 'HVSI', 'SOCI', 'ASI', 'BSI', 'MSAVI']) \
.addBands(elevation) \
.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=100,maxPixels=1e10)

modis_lai_stats = modis_lai_imagery.select(['Lai']) \
.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=100,maxPixels=1e10)

modis_vegetation_stats = modis_vegetation_imagery.select(['NDVI','EVI']) \
.reduceRegion(reducer=ee.Reducer.mean(),geometry=roi,scale=100,maxPixels=1e10)


USDA_stats = USDA_imagery.select(['ssm']) \
.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=100,maxPixels=1e10)

indices = sentinel_2_stats.getInfo()
modis_lai_indices = modis_lai_stats.getInfo()
modis_vegetation_indices = modis_vegetation_stats.getInfo()
usda_indices = USDA_stats.getInfo()
landsat8_indices = landsat8_stats.getInfo()
landsat9_indices = landsat9_stats.getInfo()

dictionary = {}
dictionary['field_id'] = field_id
dictionary['coorrdinates']= roi.getInfo()['coordinates'][0]
dictionary['date'] = year['year']
dictionary['Annual NDVI'] = indices.get('NDVI')
dictionary['Annual EVI'] = indices.get('EVI')
dictionary['Annual GNDVI'] = indices.get('GNDVI')
dictionary['Annual SAVI'] = indices.get('SAVI')
dictionary['Annual B1'] = indices.get('B1')
dictionary['Annual B2'] = indices.get('B2')
dictionary['Annual B3'] = indices.get('B3')
dictionary['Annual B4'] = indices.get('B4')
dictionary['Annual B5'] = indices.get('B5')
dictionary['Annual B6'] = indices.get('B6')
dictionary['Annual B7'] = indices.get('B7')
dictionary['Annual B8'] = indices.get('B8')
dictionary['Annual B9'] = indices.get('B9')
dictionary['Annual B11'] = indices.get('B11')
dictionary['Annual B12'] = indices.get('B12')

dictionary['Annual VCI'] = indices.get('VCI')
dictionary['Annual TVI'] = indices.get('TVI')
dictionary['Annual BI'] = indices.get('BI')
dictionary['Annual BI2'] = indices.get('BI2')
dictionary['Annual CI'] = indices.get('CI')
dictionary['Annual CI1'] = indices.get('CI1')
dictionary['Annual SATVI'] = indices.get('SATVI')
dictionary['Annual HVSI'] = indices.get('HVSI')
dictionary['Annual SOCI'] = indices.get('SOCI')
dictionary['Annual ASI'] = indices.get('ASI')
dictionary['Annual BSI'] = indices.get('BSI')
dictionary['Annual MSAVI'] = indices.get('MSAVI')

dictionary['Elevation'] = indices.get('elevation')

dictionary['Annual SR8_B1'] = landsat8_indices.get('SR_B1')
dictionary['Annual SR8_B2'] = landsat8_indices.get('SR_B2')
dictionary['Annual SR8_B3'] = landsat8_indices.get('SR_B3')
dictionary['Annual SR8_B4'] = landsat8_indices.get('SR_B4')
dictionary['Annual SR8_B5'] = landsat8_indices.get('SR_B5')
dictionary['Annual SR8_B6'] = landsat8_indices.get('SR_B6')
dictionary['Annual SR8_B7'] = landsat8_indices.get('SR_B7')
dictionary['Annual NBR_8'] = landsat8_indices.get('NBR')
dictionary['Annual NDMI_8'] = landsat8_indices.get('NDMI')
dictionary['Annual NDWI_8'] = landsat8_indices.get('NDWI')
dictionary['Annual NDBI_8'] = landsat8_indices.get('NDBI')
dictionary['Annual NDBaI_8'] = landsat8_indices.get('NDBaI')
dictionary['Annual MNDWI_8'] = landsat8_indices.get('MNDWI')
dictionary['Annual NDVI_8'] = landsat8_indices.get('NDVI')
dictionary['Annual GNDVI_8'] = landsat8_indices.get('GNDVI')
dictionary['Annual EVI_8'] = landsat8_indices.get('EVI')






dictionary['Annual SR9_B1'] = landsat9_indices.get('SR_B1')
dictionary['Annual SR9_B2'] = landsat9_indices.get('SR_B2')
dictionary['Annual SR9_B3'] = landsat9_indices.get('SR_B3')
dictionary['Annual SR9_B4'] = landsat9_indices.get('SR_B4')
dictionary['Annual SR9_B5'] = landsat9_indices.get('SR_B5')
dictionary['Annual SR9_B6'] = landsat9_indices.get('SR_B6')
dictionary['Annual SR9_B7'] = landsat9_indices.get('SR_B7')
dictionary['Annual NBR_9'] = landsat9_indices.get('NBR')
dictionary['Annual NDMI_9'] = landsat9_indices.get('NDMI')
dictionary['Annual NDWI_9'] = landsat9_indices.get('NDWI')
dictionary['Annual NDBI_9'] = landsat9_indices.get('NDBI')
dictionary['Annual NDBaI_9'] = landsat9_indices.get('NDBaI')
dictionary['Annual MNDWI_9'] = landsat9_indices.get('MNDWI')
dictionary['Annual NDVI_9'] = landsat9_indices.get('NDVI')
dictionary['Annual GNDVI_9'] = landsat9_indices.get('GNDVI')
dictionary['Annual EVI_9'] = landsat9_indices.get('EVI')

dictionary['Annual MODIS LAI'] = modis_lai_indices.get('Lai')

dictionary['Annual MODIS NDVI'] = normalize_modis_value(modis_vegetation_indices.get('NDVI'))
dictionary['Annual MODIS EVI'] = normalize_modis_value(modis_vegetation_indices.get('EVI'))

dictionary['Annual MOISTURE'] = usda_indices.get('ssm')

dictionary['Area'] = area
dictionary

In [ ]:
state_level_indices = []

In [ ]:
start_date = '2023-01-01'
end_date = '2023-12-31'
roi = sugarcane_tx.geometry()

sentinel2_data = sentinel2 \
.filterDate(start_date, end_date)


landsat8_data = landsat8 \
.filterDate(start_date, end_date)


modis_lai = modis_lai_data \
.filterDate(start_date, end_date)

modis_vegetation = modis_vegetation_data \
.filterDate(start_date, end_date)

USDA_SoilData_data = USDA_SoilData \
.filterDate(start_date, end_date)

landsat8_imagery = landsat8_data.mosaic().select(['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7','NBR','NDVI','GNDVI','EVI','NDMI','NDWI','NDBI','NDBaI','MNDWI'])
sentinel_2_imagery = sentinel2_data.median().select(['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'B11', 'B12', 'NDVI', 'EVI', 'GNDVI','SAVI','VCI', 'TVI', 'BI', 'BI2', 'CI', 'CI1', 'SATVI', 'HVSI', 'SOCI', 'ASI', 'BSI', 'MSAVI'])
modis_lai_imagery = modis_lai.mosaic().select(['Lai'])
modis_vegetation_imagery = modis_vegetation.mosaic().select('NDVI','EVI')
USDA_imagery = USDA_SoilData_data.mosaic().select(['ssm'])




elevation = NASA_srtm.clip(roi).log().divide(10).clamp(0, 1).toFloat()

landsat8_stats = landsat8_imagery.select(['SR_B1', 'SR_B2', 'SR_B3', 'SR_B4', 'SR_B5', 'SR_B6', 'SR_B7','NBR','NDVI','GNDVI','EVI','NDMI','NDWI','NDBI','NDBaI','MNDWI']) \
.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=250, maxPixels=1e13 )


sentinel_2_stats = sentinel_2_imagery.select(['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'B11', 'B12', 'NDVI', 'EVI', 'GNDVI','SAVI','VCI', 'TVI', 'BI', 'BI2', 'CI', 'CI1', 'SATVI', 'HVSI', 'SOCI', 'ASI', 'BSI', 'MSAVI']) \
.addBands(elevation) \
.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=250, maxPixels=1e13 )

modis_lai_stats = modis_lai_imagery.select(['Lai']) \
.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=250, maxPixels=1e13 )

modis_vegetation_stats = modis_vegetation_imagery.select(['NDVI','EVI']) \
.reduceRegion(reducer=ee.Reducer.mean(),geometry=roi,scale=250, maxPixels=1e13 )


USDA_stats = USDA_imagery.select(['ssm']) \
.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi,scale=250, maxPixels=1e13 )

indices = sentinel_2_stats.getInfo()
print(indices)
modis_lai_indices = modis_lai_stats.getInfo()
modis_vegetation_indices = modis_vegetation_stats.getInfo()
usda_indices = USDA_stats.getInfo()
landsat8_indices = landsat8_stats.getInfo()


dictionary = {}
dictionary['date'] = 2022
dictionary['Annual Sentinel 2 NDVI'] = indices.get('NDVI')
dictionary['Annual Sentinel 2 EVI'] = indices.get('EVI')
dictionary['Annual Sentinel 2 GNDVI'] = indices.get('GNDVI')
dictionary['Annual Sentinel 2 SAVI'] = indices.get('SAVI')
dictionary['Annual Sentinel 2 B1'] = indices.get('B1')
dictionary['Annual Sentinel 2 B2'] = indices.get('B2')
dictionary['Annual Sentinel 2 B3'] = indices.get('B3')
dictionary['Annual Sentinel 2 B4'] = indices.get('B4')
dictionary['Annual Sentinel 2 B5'] = indices.get('B5')
dictionary['Annual Sentinel 2 B6'] = indices.get('B6')
dictionary['Annual Sentinel 2 B7'] = indices.get('B7')
dictionary['Annual Sentinel 2 B8'] = indices.get('B8')
dictionary['Annual Sentinel 2 B9'] = indices.get('B9')
dictionary['Annual Sentinel 2 B11'] = indices.get('B11')
dictionary['Annual Sentinel 2 B12'] = indices.get('B12')

dictionary['Annual Sentinel 2 VCI'] = indices.get('VCI')
dictionary['Annual Sentinel 2 TVI'] = indices.get('TVI')
dictionary['Annual Sentinel 2 BI'] = indices.get('BI')
dictionary['Annual Sentinel 2 BI2'] = indices.get('BI2')
dictionary['Annual Sentinel 2 CI'] = indices.get('CI')
dictionary['Annual Sentinel 2 CI1'] = indices.get('CI1')
dictionary['Annual Sentinel 2 SATVI'] = indices.get('SATVI')
dictionary['Annual Sentinel 2 HVSI'] = indices.get('HVSI')
dictionary['Annual Sentinel 2 SOCI'] = indices.get('SOCI')
dictionary['Annual Sentinel 2 ASI'] = indices.get('ASI')
dictionary['Annual Sentinel 2 BSI'] = indices.get('BSI')
dictionary['Annual Sentinel 2 MSAVI'] = indices.get('MSAVI')

dictionary['Annual Sentinel 2 Elevation'] = indices.get('elevation')

dictionary['Annual SR8_B1'] = landsat8_indices.get('SR_B1')
dictionary['Annual SR8_B2'] = landsat8_indices.get('SR_B2')
dictionary['Annual SR8_B3'] = landsat8_indices.get('SR_B3')
dictionary['Annual SR8_B4'] = landsat8_indices.get('SR_B4')
dictionary['Annual SR8_B5'] = landsat8_indices.get('SR_B5')
dictionary['Annual SR8_B6'] = landsat8_indices.get('SR_B6')
dictionary['Annual SR8_B7'] = landsat8_indices.get('SR_B7')
dictionary['Annual NBR_8'] = landsat8_indices.get('NBR')
dictionary['Annual NDMI_8'] = landsat8_indices.get('NDMI')
dictionary['Annual NDWI_8'] = landsat8_indices.get('NDWI')
dictionary['Annual NDBI_8'] = landsat8_indices.get('NDBI')
dictionary['Annual NDBaI_8'] = landsat8_indices.get('NDBaI')
dictionary['Annual MNDWI_8'] = landsat8_indices.get('MNDWI')
dictionary['Annual NDVI_8'] = landsat8_indices.get('NDVI')
dictionary['Annual GNDVI_8'] = landsat8_indices.get('GNDVI')
dictionary['Annual EVI_8'] = landsat8_indices.get('EVI')




dictionary['Annual MODIS LAI'] = modis_lai_indices.get('Lai')

dictionary['Annual MODIS NDVI'] = normalize_modis_value(modis_vegetation_indices.get('NDVI'))
dictionary['Annual MODIS EVI'] = normalize_modis_value(modis_vegetation_indices.get('EVI'))

dictionary['Annual MOISTURE'] = usda_indices.get('ssm')

state_level_indices.append(dictionary)

{'ASI': -33.141419448358, 'B1': 2181.1900563408553, 'B11': 3930.6317490442957, 'B12': 3255.653025065278, 'B2': 2178.0151335212477, 'B3': 2441.4233780682403, 'B4': 2498.4411136350227, 'B5': 2932.567160414452, 'B6': 4396.798493781644, 'B7': 4933.907149496655, 'B8': 4894.803470349268, 'B9': 5205.28617250264, 'BI': 5475.726584397714, 'BI2': 3588.1626707813703, 'BSI': -0.44139644958111385, 'CI': 0.44137244121683167, 'CI1': -0.2976512254352804, 'EVI': 0.8229620973295511, 'GNDVI': 0.20058359337936868, 'HVSI': 1271.380613272748, 'MSAVI': 0.2976179695026252, 'NDVI': 0.1771467334632989, 'SATVI': 0.1770519651038373, 'SAVI': 0.26577299287973455, 'SOCI': -205.95697529302092, 'TVI': 0.0885675166539727, 'VCI': 22.145186315503103, 'elevation': 0.28191974894330096}

In [ ]:
df = pd.DataFrame(state_level_indices)
df

,date,Annual Sentinel 2 NDVI,Annual Sentinel 2 EVI,Annual Sentinel 2 GNDVI,Annual Sentinel 2 SAVI,Annual Sentinel 2 B1,Annual Sentinel 2 B2,Annual Sentinel 2 B3,Annual Sentinel 2 B4,Annual Sentinel 2 B5,...,Annual NDBI_8,Annual NDBaI_8,Annual MNDWI_8,Annual NDVI_8,Annual GNDVI_8,Annual EVI_8,Annual MODIS LAI,Annual MODIS NDVI,Annual MODIS EVI,Annual MOISTURE
0,2018,0.510696,1.225484,0.514664,0.765934,293.707347,489.203926,797.569324,795.255244,1232.739087,...,-0.055021,0.097596,-0.195051,0.242145,0.246671,1.482898,2.340763,-0.443191,-0.497763,4.638592
1,2019,0.575887,1.824435,0.521776,0.863708,612.372038,683.985897,1004.335344,835.873543,1379.315789,...,-0.045450,0.091104,-0.184301,0.224064,0.226561,1.200796,3.505672,-0.008984,-0.244918,4.671412
2,2021,0.609611,1.869806,0.546004,0.914302,564.028831,650.920773,987.674162,811.473844,1367.469471,...,-0.104146,0.111388,-0.169284,0.272159,0.267744,1.507070,6.618510,0.156520,-0.130540,7.370429
3,2022,0.177147,0.822962,0.200584,0.265773,2181.190056,2178.015134,2441.423378,2498.441114,2932.567160,...,-0.056943,0.101082,-0.174731,0.233847,0.228738,1.744777,3.853830,-0.094747,-0.335306,1.996733

In [ ]:

# Save the DataFrame as a CSV file
df.to_csv('State Level.csv', index=False)

# Download the CSV file in Google Colab
from google.colab import files
files.download('State Level.csv')